/**
 * Frequency Match — public client config (generated by scripts/setup-supabase.ps1)
 * Never put secret keys here.
 */
window.FM_CONFIG = {
  SUPABASE_URL: 'https://qqlodxrzisbwapjcvjoj.supabase.co',
  SUPABASE_PUBLISHABLE_KEY: 'sb_publishable_SPYW_M9_RCnKJOz8RhAIUA_CC2j3SSi',
  STRIPE_PRICE_ID: '',
  FUNCTIONS_BASE: 'https://qqlodxrzisbwapjcvjoj.supabase.co/functions/v1',
  FREE_MATCH_LIMIT: 3,
  PRO_PRICE_LABEL: '$4.99/mo',
  PRO_NAME: 'Frequency Pro',
  SITE_NAME: 'Frequency Match',
};
